### ISSUE TITLE
프로필 이미지 파일 전송 후 변경 전 디비 값이 반환되는 문제

### ISSUE THREAD

**Issue by doodlerrr** [nowhereim/ASOproject#12]
프로필 이미지 파일 전송 후 변경 전 디비 값이 반환되는 문제

문제 상황
프로필 이미지 파일 전송 완료
-> db 값 변경 잘 됨
-> 그런데 반환되는 값은 변경 전 디비 값
-> 잘 보니까 representProfile이랑 profileImage는 변경된 값으로 잘 반영되어있는데
     이상하게 req.body로 받은 값 들만 변경 전 디비에 있던 값들이 응답 값으로 들어간다.

**Comment by nowhereim** [comment]
Comeplete

**Comment by nowhereim** [comment]
해결되었습니다.
